name: Run tests with allure report
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    env:
      SUBPROJECT_NAME: aquality-selenium-template-cucumber
      GH_PAGES_URL: https://mialeska.github.io/aquality-selenium-java-template
      
    concurrency: maven-tests
      
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
           ./scripts/InstallChrome.sh
      - name: Test with Maven
        id: maven_tests
        run: mvn clean test -pl ${{ env.SUBPROJECT_NAME }} -am

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ${{ env.SUBPROJECT_NAME }}/target/allure-results
          subfolder: ${{ env.SUBPROJECT_NAME }}
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 1

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: ${{ steps.maven_tests.outcome }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ env.GH_PAGES_URL }}/${{ env.SUBPROJECT_NAME }}/${{ github.run_number }}/
